version: '3'

services:
  app1:
    build:
      context: ./app1
    ports:
      - "3001:3000"

  app2:
    build:
      context: ./app2
    ports:
      - "3002:3000"

  nginx:
    build:
      context: .
    ports:
      - "8080:80"
    links:
      - app1
      - app2

